// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4llwJCdmyIYVq0BoSen-0MxHLJky3_ak',
    appId: '1:1082152006247:web:2336a46f51a0c73340dac2',
    messagingSenderId: '1082152006247',
    projectId: 'aidify-ef75d',
    authDomain: 'aidify-ef75d.firebaseapp.com',
    storageBucket: 'aidify-ef75d.firebasestorage.app',
    measurementId: 'G-XTCL00M948',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9L9geQqZc2h1TPqjalNBB6KbZ1YbvNJ0',
    appId: '1:1082152006247:android:de0e5ca71bf126a140dac2',
    messagingSenderId: '1082152006247',
    projectId: 'aidify-ef75d',
    storageBucket: 'aidify-ef75d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxQHy9Jgv2i0hHkyPxq-gXhNskjjN2f5E',
    appId: '1:1082152006247:ios:37e633c59f2b0ca840dac2',
    messagingSenderId: '1082152006247',
    projectId: 'aidify-ef75d',
    storageBucket: 'aidify-ef75d.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxQHy9Jgv2i0hHkyPxq-gXhNskjjN2f5E',
    appId: '1:1082152006247:ios:37e633c59f2b0ca840dac2',
    messagingSenderId: '1082152006247',
    projectId: 'aidify-ef75d',
    storageBucket: 'aidify-ef75d.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4llwJCdmyIYVq0BoSen-0MxHLJky3_ak',
    appId: '1:1082152006247:web:19f14acc0354cbc640dac2',
    messagingSenderId: '1082152006247',
    projectId: 'aidify-ef75d',
    authDomain: 'aidify-ef75d.firebaseapp.com',
    storageBucket: 'aidify-ef75d.firebasestorage.app',
    measurementId: 'G-DWNJ58LH4T',
  );
}
